public class LinkedIntListClient {
    public static void main(String[] args) {
        System.out.println("Exercise #1: set method");
        LinkedIntList list1 = new LinkedIntList();
        list1.add(11);
        list1.add(22);
        list1.add(33);
        list1.add(44);
        list1.add(66);
        System.out.println("list1 before = " + list1.toString());
        list1.set(4, 55);
        System.out.println("list1 after = " + list1.toString());
        System.out.println();

        System.out.println("Exercise #2: min method");
        LinkedIntList list2 = new LinkedIntList();
        list2.add(3);
        list2.add(1);
        list2.add(5);
        list2.add(7);
        list2.add(-1);
        System.out.println("list2 = " + list2.toString());
        System.out.println("minimum value = " + list2.min());
        System.out.println();

        System.out.println("Exercise #3: isSorted method");
        LinkedIntList list3a = new LinkedIntList();
        list3a.add(1);
        list3a.add(2);
        list3a.add(3);
        list3a.add(3);
        list3a.add(4);
        System.out.println("list3a = " + list3a.toString());
        System.out.println("list3a is sorted: " + list3a.isSorted());
        System.out.println();

        LinkedIntList list3b = new LinkedIntList();
        list3b.add(1);
        list3b.add(2);
        list3b.add(1);
        list3b.add(3);
        list3b.add(4);
        System.out.println("list3b = " + list3b.toString());
        System.out.println("list3b is sorted: " + list3b.isSorted());
        System.out.println();

        System.out.println("Exercise #4: lastIndexOf method");
        LinkedIntList list4 = new LinkedIntList();
        list4.add(1);
        list4.add(18);
        list4.add(2);
        list4.add(7);
        list4.add(18);
        list4.add(39);
        list4.add(18);
        list4.add(40);
        System.out.println("list4 = " + list4.toString());
        System.out.println("the last index of value 18 is: " + list4.lastIndexOf(18));
        System.out.println();

        System.out.println("Exercise #5: countDuplicates method");
        LinkedIntList list5 = new LinkedIntList();
        list5.add(1);
        list5.add(1);
        list5.add(1);
        list5.add(3);
        list5.add(3);
        list5.add(6);
        list5.add(9);
        list5.add(15);
        list5.add(15);
        list5.add(23);
        list5.add(23);
        list5.add(23);
        list5.add(40);
        list5.add(40);
        System.out.println("list5 = " + list5.toString());
        System.out.println("The total duplicates is " + list5.countDuplicates());
        System.out.println();

        System.out.println("Exercise #6: hasTwoConsecutive method");
        LinkedIntList list6 = new LinkedIntList();
        list6.add(1);
        list6.add(18);
        list6.add(2);
        list6.add(7);
        list6.add(8);
        list6.add(39);
        list6.add(18);
        list6.add(40);
        System.out.println("list6 = " + list6.toString());
        System.out.println("The list contains an adjacent consecutive pair: " + list6.hasTwoConsecutive());
        System.out.println();

        System.out.println("Exercise #7: deleteBack method");
        LinkedIntList list7 = new LinkedIntList();
        list7.add(1);
        list7.add(2);
        list7.add(3);
        list7.add(4);
        list7.add(5);
        System.out.println("list7 before = " + list7.toString());
        int delete = list7.deleteBack();
        System.out.println("list7 after = " + list7.toString());
        System.out.println("The value deleted is: " + delete);
        System.out.println();

        System.out.println("Exercise #8: switchPairs method");
        LinkedIntList list8 = new LinkedIntList();
        list8.add(10);
        list8.add(25);
        list8.add(31);
        list8.add(47);
        list8.add(52);
        list8.add(68);
        list8.add(77);
        System.out.println("list8 before = " + list8.toString());
        list8.switchPairs();
        System.out.println("list8 after = " + list8.toString());
        System.out.println();

        System.out.println("Exercise #9: stutter method");
        LinkedIntList list9 = new LinkedIntList();
        list9.add(1);
        list9.add(8);
        list9.add(19);
        list9.add(4);
        list9.add(17);
        System.out.println("list9 before = " + list9.toString());
        list9.stutter();
        System.out.println("list9 after = " + list9.toString());
        System.out.println();

        System.out.println("Exercise #10: stretch method");
        LinkedIntList list10 = new LinkedIntList();
        list10.add(18);
        list10.add(7);
        list10.add(4);
        list10.add(24);
        list10.add(11);
        System.out.println("list10 before = " + list10.toString());
        list10.stretch(3);
        System.out.println("list10 after = " + list10.toString());
        System.out.println();

        System.out.println("Exercise #11: compress method");
        LinkedIntList list11 = new LinkedIntList();
        list11.add(1);
        list11.add(7);
        list11.add(3);
        list11.add(9);
        list11.add(4);
        list11.add(6);
        list11.add(5);
        System.out.println("list11 before = " + list11.toString());
        list11.compress();
        System.out.println("list11 after = " + list11.toString());
        System.out.println();

        System.out.println("Exercise #12: split method");
        LinkedIntList list12 = new LinkedIntList();
        list12.add(8);
        list12.add(7);
        list12.add(-4);
        list12.add(19);
        list12.add(0);
        list12.add(43);
        list12.add(-8);
        list12.add(-7);
        list12.add(-2);
        System.out.println("list12 before = " + list12.toString());
        list12.split();
        System.out.println("list12 after = " + list12.toString());
        System.out.println();

        System.out.println("Exercise #13: transferFrom method");
        LinkedIntList list13a = new LinkedIntList();
        list13a.add(8);
        list13a.add(17);
        list13a.add(2);
        list13a.add(4);
        LinkedIntList list13b = new LinkedIntList();
        list13b.add(1);
        list13b.add(2);
        list13b.add(3);
        System.out.println("list13a before = " + list13a.toString());
        System.out.println("list13b before = " + list13b.toString());
        list13b.transferFrom(list13a);
        System.out.println("list13a after = " + list13a.toString());
        System.out.println("list13b after = " + list13b.toString());
        System.out.println();

        System.out.println("Exercise #14: removeAll method");
        LinkedIntList list14 = new LinkedIntList();
        list14.add(3);
        list14.add(9);
        list14.add(4);
        list14.add(2);
        list14.add(3);
        list14.add(8);
        list14.add(17);
        list14.add(4);
        list14.add(3);
        list14.add(18);
        System.out.println("list14 before = " + list14.toString());
        list14.removeAll(3);
        System.out.println("list14 after = " + list14.toString());
        System.out.println();

        System.out.println("Exercise #15: equals method");
        LinkedIntList list15a = new LinkedIntList();
        list15a.add(1);
        list15a.add(2);
        list15a.add(3);
        list15a.add(4);
        list15a.add(5);
        LinkedIntList list15b = new LinkedIntList();
        list15b.add(1);
        list15b.add(2);
        list15b.add(3);
        list15b.add(4);
        list15b.add(5);
        System.out.println("list15a = " + list15a.toString());
        System.out.println("list15b = " + list15b.toString());
        System.out.println("The two lists are equal: " + list15a.equals(list15b));
        System.out.println();

        System.out.println("Exercise #16: removeEvens method");
        LinkedIntList list16a = new LinkedIntList();
        list16a.add(8);
        list16a.add(13);
        list16a.add(17);
        list16a.add(4);
        list16a.add(9);
        list16a.add(12);
        list16a.add(98);
        list16a.add(41);
        list16a.add(7);
        list16a.add(23);
        list16a.add(0);
        list16a.add(92);
        System.out.println("list16a before = " + list16a.toString());
        LinkedIntList list16b = list16a.removeEvens();
        System.out.println("list16a after = " + list16a.toString());
        System.out.println("list16b = " + list16b.toString());
        System.out.println();

        System.out.println("Exercise #17: removeRangemethod");
        LinkedIntList list17 = new LinkedIntList();
        list17.add(8);
        list17.add(13);
        list17.add(17);
        list17.add(4);
        list17.add(9);
        list17.add(12);
        list17.add(98);
        list17.add(41);
        list17.add(7);
        list17.add(23);
        list17.add(0);
        list17.add(92);
        System.out.println("list17 before = " + list17.toString());
        list17.removeRange(3, 8);
        System.out.println("list17 after = " + list17.toString());

        System.out.println("Exercise #18: doubleList method");
        LinkedIntList list18 = new LinkedIntList();
        list18.add(1);
        list18.add(3);
        list18.add(2);
        list18.add(7);
        System.out.println("list18 before = " + list18.toString());
        list18.doubleList();
        System.out.println("list18 after = " + list18.toString());
        System.out.println();

        System.out.println("Exercise #19: rotate method");
        LinkedIntList list19 = new LinkedIntList();
        list19.add(8);
        list19.add(23);
        list19.add(19);
        list19.add(7);
        list19.add(45);
        list19.add(98);
        list19.add(102);
        list19.add(4);
        System.out.println("list19 before = " + list19.toString());
        list19.rotate();
        System.out.println("list19 after = " + list19.toString());
        System.out.println();

        System.out.println("Exercise #20: shift method");
        LinkedIntList list20 = new LinkedIntList();
        list20.add(10);
        list20.add(31);
        list20.add(42);
        list20.add(23);
        list20.add(44);
        list20.add(75);
        list20.add(86);
        System.out.println("list20 before = " + list20.toString());
        list20.shift();
        System.out.println("list20 after = " + list20.toString());
        System.out.println();

        System.out.println("Exercise #21: reverse method");
        LinkedIntList list21 = new LinkedIntList();
        list21.add(1);
        list21.add(8);
        list21.add(19);
        list21.add(4);
        list21.add(17);
        System.out.println("list21 before = " + list21.toString());
        list21.reverse();
        System.out.println("list21 after = " + list21.toString());
        System.out.println();
    }
}